# Generated by Django 4.2.4 on 2023-12-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_postattachment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='image',
            field=models.ImageField(upload_to='post_attachments/<django.db.models.query_utils.DeferredAttribute object at 0x0000022A143F2750>'),
        ),
    ]
