# Generated by Django 4.2.4 on 2023-12-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0011_post_likes_count_alter_postattachment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='image',
            field=models.ImageField(upload_to='post_attachments/<django.db.models.query_utils.DeferredAttribute object at 0x000001319C73A9D0>'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, to='post.like'),
        ),
    ]
