# Generated by Django 4.2.4 on 2023-12-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_like_created_for_alter_postattachment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_for',
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='image',
            field=models.ImageField(upload_to='post_attachments/<django.db.models.query_utils.DeferredAttribute object at 0x000001C2D3D2FE50>'),
        ),
    ]
