# Generated by Django 4.2.4 on 2023-12-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_rename_post_comment_commented_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='image',
            field=models.ImageField(upload_to='post_attachments/<django.db.models.query_utils.DeferredAttribute object at 0x00000274427242D0>'),
        ),
    ]
