# Generated by Django 4.2.4 on 2023-12-18 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_alter_postattachment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post_liked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='post.post'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='image',
            field=models.ImageField(upload_to='post_attachments/<django.db.models.query_utils.DeferredAttribute object at 0x000001FFB90E42D0>'),
        ),
    ]
