# Generated by Django 4.2.4 on 2023-12-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_alter_postattachment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattachment',
            name='image',
        ),
    ]
