# Generated by Django 4.2.4 on 2024-01-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='image',
            field=models.ImageField(null=True, upload_to='post_attachments/'),
        ),
    ]
