# Generated by Django 4.2.4 on 2024-01-02 14:03

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_postattachment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='image',
            field=models.ImageField(null=True, upload_to=post.models.user_post_path),
        ),
    ]
