# Generated by Django 4.2.4 on 2023-12-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-modified_at',)},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='modified_at_formatted',
            new_name='modified_at',
        ),
    ]
