# Generated by Django 4.2.4 on 2023-12-27 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_remove_conversation_users_conversation_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='users',
        ),
        migrations.AddField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
