# Generated by Django 4.2.4 on 2023-12-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_conversation_users_conversation_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ('created_at',)},
        ),
    ]
