# Generated by Django 4.2.4 on 2023-12-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
