# Generated by Django 4.2.4 on 2024-01-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_friendrequest_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='email',
        ),
    ]
