# Generated by Django 4.2.4 on 2024-01-31 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_categories_alter_user_gender_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='account.categories'),
        ),
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loca', to='account.locations'),
        ),
    ]
