# Generated by Django 4.2.4 on 2024-01-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_locations_body_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
