# Generated by Django 4.2.4 on 2024-01-31 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='body_test',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='category',
        ),
    ]
