# Generated by Django 4.2.4 on 2024-02-01 23:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_locations_body_test_remove_locations_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.locations'),
        ),
    ]
