# Generated by Django 4.2.4 on 2024-02-01 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_user_locations_delete_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.locations'),
        ),
    ]
