# Generated by Django 4.2.4 on 2024-02-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_hobby_user_hobbies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hobbies',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
