# Generated by Django 4.2.4 on 2024-02-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_delete_locations_remove_user_hobbies_delete_hobby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
